#
# This file is sourced by all `zsh` shells.
# It is read after /etc/zshenv.
#

# Source xsh or error out silently.
source "${XSH_DIR:-${XDG_CONFIG_HOME:-$HOME/.config}/xsh}/xsh.sh" 2>/dev/null ||
  return 1

xsh runcom env
